[package]
name = "opengl_engine"
version = "0.1.0"
authors = ["Ross Marc <ross.adshead@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
